### ISSUE TITLE
APB Slave module missing for apb_master.v

### ISSUE THREAD

**Issue by Anmol-wq** [lucky-wfw/ARM_AMBA_Design#2]
Hi. I am new to the field of protocols and RTL Design. I was using this repo for learning the concepts i have studied in the specs, and see a possible implementation for the same. When i did behavioural simulation for apb_master_tb.v, i was received with the error of apb_slave module missing. Also, on commenting out the slave portion, the results doesn't seem proper  it seems. Am i missing something? Thanks in advance!

**Comment by lucky-wfw** [comment]
Thanks for the reminder.
After checking, the module APB Slave did not upload.
Since it was a long time ago, some of the code was lost.
However, APB Slvae is simple and has many methods to implement. It can be done by using a state machine directly according to the sequence on the SPEC.
Later, if I have time, I will rewrite it and upload it again, thank you.
